### ISSUE TITLE
Syntax unknown for this lab

### ISSUE THREAD

**Issue by jhr7139** [learn-co-curriculum/meal-choice#11]
I have not studied before the elements of the syntax required for this lab. Resources do not contain any explanations whatsoever.  Help? :)

Heading to the library to borrow a book and study in the meantime.

**Comment by Joll59** [comment]
@jhr7139 Thank you for your patience. 
generally you can ask questions using Slack or the ask a question feature on Learn.co. 
Closing this issue for now.
