### ISSUE TITLE
re: Possible glitch on Introductory Default Argument 2

### ISSUE THREAD

**Issue by loma7** [learn-co-curriculum/meal-choice#9]
I'm running tests for the Intro Default Arugement 2 lab. Tests are failing. Code is pretty straight forward and I posted on Stackoverflow and people there have ran the code as well with no errors thrown. Wondering if someone can tell me whether there is a glitch or possible look at my code let me know if its my code thats the problem?

**Comment by AnnJohn** [comment]
hi @loma7 this looks like it would be something specifically with your code. Could you please use the Ask a Question tool in Learn and someone from our support team will help you out? Thanks
